local Sets = {
	classic = {
		id = "classic",
		displayName = "Classic Set",
		assetGroup = "Examples",
		assetModel = "Classic",
		rollDisplay = {
			displayName = "Classic",
			rarity = "Basic",
			chance = 100,
			passiveIncomePerSecond = 100,
			color = Color3.fromRGB(255, 255, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "classic_head",
			Torso = "classic_torso",
			LeftArm = "classic_left_arm",
			RightArm = "classic_right_arm",
			LeftLeg = "classic_left_leg",
			RightLeg = "classic_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 4,
			luckBonus = 0.1,
			rollSpeedBonus = 0.05,
		},
	},

	test_alt = {
		id = "test_alt",
		displayName = "Test Alt Set",
		assetGroup = "Examples",
		assetModel = "TestAlt",
		rollDisplay = {
			displayName = "Test Alt",
			rarity = "Clean",
			chance = 500,
			passiveIncomePerSecond = 250,
			color = Color3.fromRGB(134, 231, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "test_alt_head",
			Torso = "test_alt_torso",
			LeftArm = "test_alt_left_arm",
			RightArm = "test_alt_right_arm",
			LeftLeg = "test_alt_left_leg",
			RightLeg = "test_alt_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 10,
			luckBonus = 0.2,
			rollSpeedBonus = 0.1,
		},
	},

	korblox_deathspeaker = {
		id = "korblox_deathspeaker",
		displayName = "Korblox Deathspeaker Set",
		assetGroup = "Korblox",
		assetModel = "Deathspeaker",
		rollDisplay = {
			displayName = "Deathspeaker",
			rarity = "Apex",
			chance = 10000000000000,
			passiveIncomePerSecond = 100,
			color = Color3.fromRGB(0, 153, 255),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Light,
		},
		piecesByRegion = {
			Head = "korblox_deathspeaker_head",
			Torso = "korblox_deathspeaker_torso",
			LeftArm = "korblox_deathspeaker_left_arm",
			RightArm = "korblox_deathspeaker_right_arm",
			LeftLeg = "korblox_deathspeaker_left_leg",
			RightLeg = "korblox_deathspeaker_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 120,
			luckBonus = 0.55,
			rollSpeedBonus = 0.3,
		},
	},

	["67_brainrot"] = {
		id = "67_brainrot",
		displayName = "67 (Brainrot) Set",
		sourceModelName = "67 (Brainrot)",
		assetGroup = "ImportedCommon",
		assetModel = "67_brainrot",
		rollDisplay = {
			displayName = "67 (Brainrot)",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "67_brainrot_head",
			Torso = "67_brainrot_torso",
			LeftArm = "67_brainrot_left_arm",
			RightArm = "67_brainrot_right_arm",
			LeftLeg = "67_brainrot_left_leg",
			RightLeg = "67_brainrot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	absolute_unit = {
		id = "absolute_unit",
		displayName = "Absolute Unit Set",
		sourceModelName = "Absolute Unit",
		assetGroup = "ImportedUncommon",
		assetModel = "absolute_unit",
		rollDisplay = {
			displayName = "Absolute Unit",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "absolute_unit_head",
			Torso = "absolute_unit_torso",
			LeftArm = "absolute_unit_left_arm",
			RightArm = "absolute_unit_right_arm",
			LeftLeg = "absolute_unit_left_leg",
			RightLeg = "absolute_unit_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	banana_bro = {
		id = "banana_bro",
		displayName = "Banana Bro Set",
		sourceModelName = "Banana Bro",
		assetGroup = "ImportedCommon",
		assetModel = "banana_bro",
		rollDisplay = {
			displayName = "Banana Bro",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "banana_bro_head",
			Torso = "banana_bro_torso",
			LeftArm = "banana_bro_left_arm",
			RightArm = "banana_bro_right_arm",
			LeftLeg = "banana_bro_left_leg",
			RightLeg = "banana_bro_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	bastion_mech_robot_recolorable = {
		id = "bastion_mech_robot_recolorable",
		displayName = "Bastion Mech Robot Set",
		sourceModelName = "Bastion mech robot [recolorable]",
		assetGroup = "ImportedRare",
		assetModel = "bastion_mech_robot_recolorable",
		rollDisplay = {
			displayName = "Bastion Mech Robot",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "bastion_mech_robot_recolorable_head",
			Torso = "bastion_mech_robot_recolorable_torso",
			LeftArm = "bastion_mech_robot_recolorable_left_arm",
			RightArm = "bastion_mech_robot_recolorable_right_arm",
			LeftLeg = "bastion_mech_robot_recolorable_left_leg",
			RightLeg = "bastion_mech_robot_recolorable_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	billy = {
		id = "billy",
		displayName = "Billy Set",
		sourceModelName = "Billy",
		assetGroup = "ImportedCommon",
		assetModel = "billy",
		rollDisplay = {
			displayName = "Billy",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "billy_head",
			Torso = "billy_torso",
			LeftArm = "billy_left_arm",
			RightArm = "billy_right_arm",
			LeftLeg = "billy_left_leg",
			RightLeg = "billy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	capybara = {
		id = "capybara",
		displayName = "Capybara Set",
		sourceModelName = "Capybara",
		assetGroup = "ImportedCommon",
		assetModel = "capybara",
		rollDisplay = {
			displayName = "Capybara",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "capybara_head",
			Torso = "capybara_torso",
			LeftArm = "capybara_left_arm",
			RightArm = "capybara_right_arm",
			LeftLeg = "capybara_left_leg",
			RightLeg = "capybara_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	cat_mech = {
		id = "cat_mech",
		displayName = "Cat Mech Set",
		sourceModelName = "Cat Mech",
		assetGroup = "ImportedUncommon",
		assetModel = "cat_mech",
		rollDisplay = {
			displayName = "Cat Mech",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "cat_mech_head",
			Torso = "cat_mech_torso",
			LeftArm = "cat_mech_left_arm",
			RightArm = "cat_mech_right_arm",
			LeftLeg = "cat_mech_left_leg",
			RightLeg = "cat_mech_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	chef_tortrdee = {
		id = "chef_tortrdee",
		displayName = "Chef Tortrdee Set",
		sourceModelName = "Chef Tortrdee",
		assetGroup = "ImportedUncommon",
		assetModel = "chef_tortrdee",
		rollDisplay = {
			displayName = "Chef Tortrdee",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "chef_tortrdee_head",
			Torso = "chef_tortrdee_torso",
			LeftArm = "chef_tortrdee_left_arm",
			RightArm = "chef_tortrdee_right_arm",
			LeftLeg = "chef_tortrdee_left_leg",
			RightLeg = "chef_tortrdee_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	davy_bazooka = {
		id = "davy_bazooka",
		displayName = "Davy Bazooka Set",
		sourceModelName = "Davy Bazooka",
		assetGroup = "ImportedRare",
		assetModel = "davy_bazooka",
		rollDisplay = {
			displayName = "Davy Bazooka",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "davy_bazooka_head",
			Torso = "davy_bazooka_torso",
			LeftArm = "davy_bazooka_left_arm",
			RightArm = "davy_bazooka_right_arm",
			LeftLeg = "davy_bazooka_left_leg",
			RightLeg = "davy_bazooka_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	deer_monster_99_nights_in_the_forest = {
		id = "deer_monster_99_nights_in_the_forest",
		displayName = "Deer Monster Set",
		sourceModelName = "Deer Monster (99 Nights in the Forest)",
		assetGroup = "ImportedRare",
		assetModel = "deer_monster_99_nights_in_the_forest",
		rollDisplay = {
			displayName = "Deer Monster",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "deer_monster_99_nights_in_the_forest_head",
			Torso = "deer_monster_99_nights_in_the_forest_torso",
			LeftArm = "deer_monster_99_nights_in_the_forest_left_arm",
			RightArm = "deer_monster_99_nights_in_the_forest_right_arm",
			LeftLeg = "deer_monster_99_nights_in_the_forest_left_leg",
			RightLeg = "deer_monster_99_nights_in_the_forest_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	el_gato = {
		id = "el_gato",
		displayName = "El Gato Set",
		sourceModelName = "El Gato",
		assetGroup = "ImportedUncommon",
		assetModel = "el_gato",
		rollDisplay = {
			displayName = "El Gato",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "el_gato_head",
			Torso = "el_gato_torso",
			LeftArm = "el_gato_left_arm",
			RightArm = "el_gato_right_arm",
			LeftLeg = "el_gato_left_leg",
			RightLeg = "el_gato_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	elemental_crystal_golem = {
		id = "elemental_crystal_golem",
		displayName = "Elemental Crystal Golem Set",
		sourceModelName = "Elemental Crystal Golem",
		assetGroup = "ImportedRare",
		assetModel = "elemental_crystal_golem",
		rollDisplay = {
			displayName = "Elemental Crystal Golem",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "elemental_crystal_golem_head",
			Torso = "elemental_crystal_golem_torso",
			LeftArm = "elemental_crystal_golem_left_arm",
			RightArm = "elemental_crystal_golem_right_arm",
			LeftLeg = "elemental_crystal_golem_left_leg",
			RightLeg = "elemental_crystal_golem_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	frost_guard_general = {
		id = "frost_guard_general",
		displayName = "Frost Guard General Set",
		sourceModelName = "Frost Guard General",
		assetGroup = "ImportedRare",
		assetModel = "frost_guard_general",
		rollDisplay = {
			displayName = "Frost Guard General",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "frost_guard_general_head",
			Torso = "frost_guard_general_torso",
			LeftArm = "frost_guard_general_left_arm",
			RightArm = "frost_guard_general_right_arm",
			LeftLeg = "frost_guard_general_left_leg",
			RightLeg = "frost_guard_general_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	gang_o_fries = {
		id = "gang_o_fries",
		displayName = "Gang O' Fries Set",
		sourceModelName = "Gang O' Fries",
		assetGroup = "ImportedCommon",
		assetModel = "gang_o_fries",
		rollDisplay = {
			displayName = "Gang O' Fries",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "gang_o_fries_head",
			Torso = "gang_o_fries_torso",
			LeftArm = "gang_o_fries_left_arm",
			RightArm = "gang_o_fries_right_arm",
			LeftLeg = "gang_o_fries_left_leg",
			RightLeg = "gang_o_fries_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	gingerbread_man = {
		id = "gingerbread_man",
		displayName = "Gingerbread Man Set",
		sourceModelName = "Gingerbread Man",
		assetGroup = "ImportedCommon",
		assetModel = "gingerbread_man",
		rollDisplay = {
			displayName = "Gingerbread Man",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "gingerbread_man_head",
			Torso = "gingerbread_man_torso",
			LeftArm = "gingerbread_man_left_arm",
			RightArm = "gingerbread_man_right_arm",
			LeftLeg = "gingerbread_man_left_leg",
			RightLeg = "gingerbread_man_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	handsome_squidward = {
		id = "handsome_squidward",
		displayName = "Handsome Squidward Set",
		sourceModelName = "Handsome Squidward",
		assetGroup = "ImportedUncommon",
		assetModel = "handsome_squidward",
		rollDisplay = {
			displayName = "Handsome Squidward",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "handsome_squidward_head",
			Torso = "handsome_squidward_torso",
			LeftArm = "handsome_squidward_left_arm",
			RightArm = "handsome_squidward_right_arm",
			LeftLeg = "handsome_squidward_left_leg",
			RightLeg = "handsome_squidward_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	headless_horseman = {
		id = "headless_horseman",
		displayName = "Headless Horseman Set",
		sourceModelName = "Headless Horseman",
		assetGroup = "ImportedLegendary",
		assetModel = "headless_horseman",
		rollDisplay = {
			displayName = "Headless Horseman",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 2200,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "headless_horseman_head",
			Torso = "headless_horseman_torso",
			LeftArm = "headless_horseman_left_arm",
			RightArm = "headless_horseman_right_arm",
			LeftLeg = "headless_horseman_left_leg",
			RightLeg = "headless_horseman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 110,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	heart = {
		id = "heart",
		displayName = "Heart Set",
		sourceModelName = "Heart",
		assetGroup = "ImportedCommon",
		assetModel = "heart",
		rollDisplay = {
			displayName = "Heart",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "heart_head",
			Torso = "heart_torso",
			LeftArm = "heart_left_arm",
			RightArm = "heart_right_arm",
			LeftLeg = "heart_left_leg",
			RightLeg = "heart_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	iron_slayer = {
		id = "iron_slayer",
		displayName = "Iron Slayer Set",
		sourceModelName = "Iron Slayer",
		assetGroup = "ImportedRare",
		assetModel = "iron_slayer",
		rollDisplay = {
			displayName = "Iron Slayer",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "iron_slayer_head",
			Torso = "iron_slayer_torso",
			LeftArm = "iron_slayer_left_arm",
			RightArm = "iron_slayer_right_arm",
			LeftLeg = "iron_slayer_left_leg",
			RightLeg = "iron_slayer_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	junkbot = {
		id = "junkbot",
		displayName = "Junkbot Set",
		sourceModelName = "Junkbot",
		assetGroup = "ImportedUncommon",
		assetModel = "junkbot",
		rollDisplay = {
			displayName = "Junkbot",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "junkbot_head",
			Torso = "junkbot_torso",
			LeftArm = "junkbot_left_arm",
			RightArm = "junkbot_right_arm",
			LeftLeg = "junkbot_left_leg",
			RightLeg = "junkbot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	knights_of_redcliff_paladin = {
		id = "knights_of_redcliff_paladin",
		displayName = "Knights Of Redcliff: Paladin Set",
		sourceModelName = "Knights of Redcliff: Paladin",
		assetGroup = "ImportedEpic",
		assetModel = "knights_of_redcliff_paladin",
		rollDisplay = {
			displayName = "Knights Of Redcliff: Paladin",
			rarity = "Prime",
			chance = 90000,
			passiveIncomePerSecond = 900,
			color = Color3.fromRGB(255, 157, 117),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "knights_of_redcliff_paladin_head",
			Torso = "knights_of_redcliff_paladin_torso",
			LeftArm = "knights_of_redcliff_paladin_left_arm",
			RightArm = "knights_of_redcliff_paladin_right_arm",
			LeftLeg = "knights_of_redcliff_paladin_left_leg",
			RightLeg = "knights_of_redcliff_paladin_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 55,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	korblox_deathspeaker_imported = {
		id = "korblox_deathspeaker_imported",
		displayName = "Korblox Deathspeaker (Imported) Set",
		sourceModelName = "Korblox Deathspeaker",
		assetGroup = "ImportedLegendary",
		assetModel = "korblox_deathspeaker_imported",
		rollDisplay = {
			displayName = "Korblox Deathspeaker (Imported)",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 2200,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "korblox_deathspeaker_imported_head",
			Torso = "korblox_deathspeaker_imported_torso",
			LeftArm = "korblox_deathspeaker_imported_left_arm",
			RightArm = "korblox_deathspeaker_imported_right_arm",
			LeftLeg = "korblox_deathspeaker_imported_left_leg",
			RightLeg = "korblox_deathspeaker_imported_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 110,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	korblox_mage = {
		id = "korblox_mage",
		displayName = "Korblox Mage Set",
		sourceModelName = "Korblox Mage",
		assetGroup = "ImportedRare",
		assetModel = "korblox_mage",
		rollDisplay = {
			displayName = "Korblox Mage",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "korblox_mage_head",
			Torso = "korblox_mage_torso",
			LeftArm = "korblox_mage_left_arm",
			RightArm = "korblox_mage_right_arm",
			LeftLeg = "korblox_mage_left_leg",
			RightLeg = "korblox_mage_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	los_tralaleritos_brainrot = {
		id = "los_tralaleritos_brainrot",
		displayName = "Los Tralaleritos (Brainrot) Set",
		sourceModelName = "Los Tralaleritos (Brainrot)",
		assetGroup = "ImportedEpic",
		assetModel = "los_tralaleritos_brainrot",
		rollDisplay = {
			displayName = "Los Tralaleritos (Brainrot)",
			rarity = "Prime",
			chance = 90000,
			passiveIncomePerSecond = 900,
			color = Color3.fromRGB(255, 157, 117),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "los_tralaleritos_brainrot_head",
			Torso = "los_tralaleritos_brainrot_torso",
			LeftArm = "los_tralaleritos_brainrot_left_arm",
			RightArm = "los_tralaleritos_brainrot_right_arm",
			LeftLeg = "los_tralaleritos_brainrot_left_leg",
			RightLeg = "los_tralaleritos_brainrot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 55,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	mahoraga = {
		id = "mahoraga",
		displayName = "Mahoraga Set",
		sourceModelName = "Mahoraga",
		assetGroup = "ImportedLegendary",
		assetModel = "mahoraga",
		rollDisplay = {
			displayName = "Mahoraga",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 2200,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "mahoraga_head",
			Torso = "mahoraga_torso",
			LeftArm = "mahoraga_left_arm",
			RightArm = "mahoraga_right_arm",
			LeftLeg = "mahoraga_left_leg",
			RightLeg = "mahoraga_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 110,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	man = {
		id = "man",
		displayName = "Man Set",
		sourceModelName = "Man   ",
		assetGroup = "ImportedCommon",
		assetModel = "man",
		rollDisplay = {
			displayName = "Man",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "man_head",
			Torso = "man_torso",
			LeftArm = "man_left_arm",
			RightArm = "man_right_arm",
			LeftLeg = "man_left_leg",
			RightLeg = "man_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	mech_golem = {
		id = "mech_golem",
		displayName = "Mech Golem Set",
		sourceModelName = "Mech Golem",
		assetGroup = "ImportedRare",
		assetModel = "mech_golem",
		rollDisplay = {
			displayName = "Mech Golem",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "mech_golem_head",
			Torso = "mech_golem_torso",
			LeftArm = "mech_golem_left_arm",
			RightArm = "mech_golem_right_arm",
			LeftLeg = "mech_golem_left_leg",
			RightLeg = "mech_golem_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	mr_roboto = {
		id = "mr_roboto",
		displayName = "Mr. Roboto Set",
		sourceModelName = "Mr. Roboto",
		assetGroup = "ImportedUncommon",
		assetModel = "mr_roboto",
		rollDisplay = {
			displayName = "Mr. Roboto",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "mr_roboto_head",
			Torso = "mr_roboto_torso",
			LeftArm = "mr_roboto_left_arm",
			RightArm = "mr_roboto_right_arm",
			LeftLeg = "mr_roboto_left_leg",
			RightLeg = "mr_roboto_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	mr_toilet = {
		id = "mr_toilet",
		displayName = "Mr. Toilet Set",
		sourceModelName = "Mr. Toilet",
		assetGroup = "ImportedUncommon",
		assetModel = "mr_toilet",
		rollDisplay = {
			displayName = "Mr. Toilet",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "mr_toilet_head",
			Torso = "mr_toilet_torso",
			LeftArm = "mr_toilet_left_arm",
			RightArm = "mr_toilet_right_arm",
			LeftLeg = "mr_toilet_left_leg",
			RightLeg = "mr_toilet_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	muscle_insane_chad_8_pack_body = {
		id = "muscle_insane_chad_8_pack_body",
		displayName = "Muscle Insane Chad 8 Pack Body Set",
		sourceModelName = "Muscle Insane Chad 8 Pack Body",
		assetGroup = "ImportedEpic",
		assetModel = "muscle_insane_chad_8_pack_body",
		rollDisplay = {
			displayName = "Muscle Insane Chad 8 Pack Body",
			rarity = "Prime",
			chance = 90000,
			passiveIncomePerSecond = 900,
			color = Color3.fromRGB(255, 157, 117),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "muscle_insane_chad_8_pack_body_head",
			Torso = "muscle_insane_chad_8_pack_body_torso",
			LeftArm = "muscle_insane_chad_8_pack_body_left_arm",
			RightArm = "muscle_insane_chad_8_pack_body_right_arm",
			LeftLeg = "muscle_insane_chad_8_pack_body_left_leg",
			RightLeg = "muscle_insane_chad_8_pack_body_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 55,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	noob_attack_mech_mobility = {
		id = "noob_attack_mech_mobility",
		displayName = "Noob Attack: Mech Mobility Set",
		sourceModelName = "Noob Attack: Mech Mobility",
		assetGroup = "ImportedUncommon",
		assetModel = "noob_attack_mech_mobility",
		rollDisplay = {
			displayName = "Noob Attack: Mech Mobility",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "noob_attack_mech_mobility_head",
			Torso = "noob_attack_mech_mobility_torso",
			LeftArm = "noob_attack_mech_mobility_left_arm",
			RightArm = "noob_attack_mech_mobility_right_arm",
			LeftLeg = "noob_attack_mech_mobility_left_leg",
			RightLeg = "noob_attack_mech_mobility_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	paper_sketch_boy_animated = {
		id = "paper_sketch_boy_animated",
		displayName = "Paper Sketch Boy Animated Set",
		sourceModelName = "Paper Sketch Boy Animated",
		assetGroup = "ImportedRare",
		assetModel = "paper_sketch_boy_animated",
		rollDisplay = {
			displayName = "Paper Sketch Boy Animated",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "paper_sketch_boy_animated_head",
			Torso = "paper_sketch_boy_animated_torso",
			LeftArm = "paper_sketch_boy_animated_left_arm",
			RightArm = "paper_sketch_boy_animated_right_arm",
			LeftLeg = "paper_sketch_boy_animated_left_leg",
			RightLeg = "paper_sketch_boy_animated_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	penguin = {
		id = "penguin",
		displayName = "Penguin Set",
		sourceModelName = "Penguin",
		assetGroup = "ImportedCommon",
		assetModel = "penguin",
		rollDisplay = {
			displayName = "Penguin",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "penguin_head",
			Torso = "penguin_torso",
			LeftArm = "penguin_left_arm",
			RightArm = "penguin_right_arm",
			LeftLeg = "penguin_left_leg",
			RightLeg = "penguin_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	pirate_swashbuckler = {
		id = "pirate_swashbuckler",
		displayName = "Pirate Swashbuckler Set",
		sourceModelName = "Pirate Swashbuckler",
		assetGroup = "ImportedUncommon",
		assetModel = "pirate_swashbuckler",
		rollDisplay = {
			displayName = "Pirate Swashbuckler",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "pirate_swashbuckler_head",
			Torso = "pirate_swashbuckler_torso",
			LeftArm = "pirate_swashbuckler_left_arm",
			RightArm = "pirate_swashbuckler_right_arm",
			LeftLeg = "pirate_swashbuckler_left_leg",
			RightLeg = "pirate_swashbuckler_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	potato_boy = {
		id = "potato_boy",
		displayName = "Potato Boy Set",
		sourceModelName = "Potato boy",
		assetGroup = "ImportedCommon",
		assetModel = "potato_boy",
		rollDisplay = {
			displayName = "Potato Boy",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "potato_boy_head",
			Torso = "potato_boy_torso",
			LeftArm = "potato_boy_left_arm",
			RightArm = "potato_boy_right_arm",
			LeftLeg = "potato_boy_left_leg",
			RightLeg = "potato_boy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	r15_korblox_deathspeaker = {
		id = "r15_korblox_deathspeaker",
		displayName = "R15 Korblox Deathspeaker Set",
		sourceModelName = "R15 - Korblox Deathspeaker",
		assetGroup = "ImportedLegendary",
		assetModel = "r15_korblox_deathspeaker",
		rollDisplay = {
			displayName = "R15 Korblox Deathspeaker",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 2200,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "r15_korblox_deathspeaker_head",
			Torso = "r15_korblox_deathspeaker_torso",
			LeftArm = "r15_korblox_deathspeaker_left_arm",
			RightArm = "r15_korblox_deathspeaker_right_arm",
			LeftLeg = "r15_korblox_deathspeaker_left_leg",
			RightLeg = "r15_korblox_deathspeaker_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 110,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	rig = {
		id = "rig",
		displayName = "Rig Set",
		sourceModelName = "Rig",
		assetGroup = "ImportedCommon",
		assetModel = "rig",
		rollDisplay = {
			displayName = "Rig",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "rig_head",
			Torso = "rig_torso",
			LeftArm = "rig_left_arm",
			RightArm = "rig_right_arm",
			LeftLeg = "rig_left_leg",
			RightLeg = "rig_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	roblox_boy = {
		id = "roblox_boy",
		displayName = "ROBLOX Boy Set",
		sourceModelName = "ROBLOX Boy",
		assetGroup = "ImportedCommon",
		assetModel = "roblox_boy",
		rollDisplay = {
			displayName = "ROBLOX Boy",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "roblox_boy_head",
			Torso = "roblox_boy_torso",
			LeftArm = "roblox_boy_left_arm",
			RightArm = "roblox_boy_right_arm",
			LeftLeg = "roblox_boy_left_leg",
			RightLeg = "roblox_boy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	roblox_girl = {
		id = "roblox_girl",
		displayName = "ROBLOX Girl Set",
		sourceModelName = "ROBLOX Girl   ",
		assetGroup = "ImportedCommon",
		assetModel = "roblox_girl",
		rollDisplay = {
			displayName = "ROBLOX Girl",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "roblox_girl_head",
			Torso = "roblox_girl_torso",
			LeftArm = "roblox_girl_left_arm",
			RightArm = "roblox_girl_right_arm",
			LeftLeg = "roblox_girl_left_leg",
			RightLeg = "roblox_girl_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	robloxian_2_0 = {
		id = "robloxian_2_0",
		displayName = "Robloxian 2.0 Set",
		sourceModelName = "Robloxian 2.0",
		assetGroup = "ImportedUncommon",
		assetModel = "robloxian_2_0",
		rollDisplay = {
			displayName = "Robloxian 2.0",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "robloxian_2_0_head",
			Torso = "robloxian_2_0_torso",
			LeftArm = "robloxian_2_0_left_arm",
			RightArm = "robloxian_2_0_right_arm",
			LeftLeg = "robloxian_2_0_left_leg",
			RightLeg = "robloxian_2_0_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	shrek = {
		id = "shrek",
		displayName = "SHREK Set",
		sourceModelName = "SHREK",
		assetGroup = "ImportedCommon",
		assetModel = "shrek",
		rollDisplay = {
			displayName = "SHREK",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "shrek_head",
			Torso = "shrek_torso",
			LeftArm = "shrek_left_arm",
			RightArm = "shrek_right_arm",
			LeftLeg = "shrek_left_leg",
			RightLeg = "shrek_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	skeleton = {
		id = "skeleton",
		displayName = "Skeleton Set",
		sourceModelName = "Skeleton  ",
		assetGroup = "ImportedCommon",
		assetModel = "skeleton",
		rollDisplay = {
			displayName = "Skeleton",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "skeleton_head",
			Torso = "skeleton_torso",
			LeftArm = "skeleton_left_arm",
			RightArm = "skeleton_right_arm",
			LeftLeg = "skeleton_left_leg",
			RightLeg = "skeleton_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	smiling_freak = {
		id = "smiling_freak",
		displayName = "Smiling Freak Set",
		sourceModelName = "Smiling Freak",
		assetGroup = "ImportedRare",
		assetModel = "smiling_freak",
		rollDisplay = {
			displayName = "Smiling Freak",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "smiling_freak_head",
			Torso = "smiling_freak_torso",
			LeftArm = "smiling_freak_left_arm",
			RightArm = "smiling_freak_right_arm",
			LeftLeg = "smiling_freak_left_leg",
			RightLeg = "smiling_freak_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	snow_gentleman = {
		id = "snow_gentleman",
		displayName = "Snow Gentleman Set",
		sourceModelName = "Snow Gentleman",
		assetGroup = "ImportedUncommon",
		assetModel = "snow_gentleman",
		rollDisplay = {
			displayName = "Snow Gentleman",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "snow_gentleman_head",
			Torso = "snow_gentleman_torso",
			LeftArm = "snow_gentleman_left_arm",
			RightArm = "snow_gentleman_right_arm",
			LeftLeg = "snow_gentleman_left_leg",
			RightLeg = "snow_gentleman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	snow_queen = {
		id = "snow_queen",
		displayName = "Snow Queen Set",
		sourceModelName = "Snow Queen",
		assetGroup = "ImportedRare",
		assetModel = "snow_queen",
		rollDisplay = {
			displayName = "Snow Queen",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "snow_queen_head",
			Torso = "snow_queen_torso",
			LeftArm = "snow_queen_left_arm",
			RightArm = "snow_queen_right_arm",
			LeftLeg = "snow_queen_left_leg",
			RightLeg = "snow_queen_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	steamboat_mouse = {
		id = "steamboat_mouse",
		displayName = "Steamboat Mouse Set",
		sourceModelName = "Steamboat Mouse",
		assetGroup = "ImportedCommon",
		assetModel = "steamboat_mouse",
		rollDisplay = {
			displayName = "Steamboat Mouse",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "steamboat_mouse_head",
			Torso = "steamboat_mouse_torso",
			LeftArm = "steamboat_mouse_left_arm",
			RightArm = "steamboat_mouse_right_arm",
			LeftLeg = "steamboat_mouse_left_leg",
			RightLeg = "steamboat_mouse_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	stinky_monkey = {
		id = "stinky_monkey",
		displayName = "Stinky Monkey Set",
		sourceModelName = "Stinky Monkey",
		assetGroup = "ImportedUncommon",
		assetModel = "stinky_monkey",
		rollDisplay = {
			displayName = "Stinky Monkey",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "stinky_monkey_head",
			Torso = "stinky_monkey_torso",
			LeftArm = "stinky_monkey_left_arm",
			RightArm = "stinky_monkey_right_arm",
			LeftLeg = "stinky_monkey_left_leg",
			RightLeg = "stinky_monkey_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	superhero = {
		id = "superhero",
		displayName = "Superhero Set",
		sourceModelName = "Superhero",
		assetGroup = "ImportedUncommon",
		assetModel = "superhero",
		rollDisplay = {
			displayName = "Superhero",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "superhero_head",
			Torso = "superhero_torso",
			LeftArm = "superhero_left_arm",
			RightArm = "superhero_right_arm",
			LeftLeg = "superhero_left_leg",
			RightLeg = "superhero_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	supreme_claus = {
		id = "supreme_claus",
		displayName = "Supreme Claus Set",
		sourceModelName = "Supreme Claus",
		assetGroup = "ImportedUncommon",
		assetModel = "supreme_claus",
		rollDisplay = {
			displayName = "Supreme Claus",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "supreme_claus_head",
			Torso = "supreme_claus_torso",
			LeftArm = "supreme_claus_left_arm",
			RightArm = "supreme_claus_right_arm",
			LeftLeg = "supreme_claus_left_leg",
			RightLeg = "supreme_claus_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	tentacled_alien = {
		id = "tentacled_alien",
		displayName = "Tentacled Alien Set",
		sourceModelName = "Tentacled Alien  ",
		assetGroup = "ImportedRare",
		assetModel = "tentacled_alien",
		rollDisplay = {
			displayName = "Tentacled Alien",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "tentacled_alien_head",
			Torso = "tentacled_alien_torso",
			LeftArm = "tentacled_alien_left_arm",
			RightArm = "tentacled_alien_right_arm",
			LeftLeg = "tentacled_alien_left_leg",
			RightLeg = "tentacled_alien_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_gnomsky_brothers = {
		id = "the_gnomsky_brothers",
		displayName = "The Gnomsky Brothers Set",
		sourceModelName = "The Gnomsky Brothers",
		assetGroup = "ImportedRare",
		assetModel = "the_gnomsky_brothers",
		rollDisplay = {
			displayName = "The Gnomsky Brothers",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "the_gnomsky_brothers_head",
			Torso = "the_gnomsky_brothers_torso",
			LeftArm = "the_gnomsky_brothers_left_arm",
			RightArm = "the_gnomsky_brothers_right_arm",
			LeftLeg = "the_gnomsky_brothers_left_leg",
			RightLeg = "the_gnomsky_brothers_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_overseer = {
		id = "the_overseer",
		displayName = "The Overseer Set",
		sourceModelName = "The Overseer",
		assetGroup = "ImportedRare",
		assetModel = "the_overseer",
		rollDisplay = {
			displayName = "The Overseer",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "the_overseer_head",
			Torso = "the_overseer_torso",
			LeftArm = "the_overseer_left_arm",
			RightArm = "the_overseer_right_arm",
			LeftLeg = "the_overseer_left_leg",
			RightLeg = "the_overseer_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_rulk_custom_colour = {
		id = "the_rulk_custom_colour",
		displayName = "The Rulk - Custom Colour Set",
		sourceModelName = "The Rulk - Custom Colour",
		assetGroup = "ImportedLegendary",
		assetModel = "the_rulk_custom_colour",
		rollDisplay = {
			displayName = "The Rulk - Custom Colour",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 2200,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "the_rulk_custom_colour_head",
			Torso = "the_rulk_custom_colour_torso",
			LeftArm = "the_rulk_custom_colour_left_arm",
			RightArm = "the_rulk_custom_colour_right_arm",
			LeftLeg = "the_rulk_custom_colour_left_leg",
			RightLeg = "the_rulk_custom_colour_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 110,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	ud_zal = {
		id = "ud_zal",
		displayName = "Ud'zal Set",
		sourceModelName = "Ud'zal",
		assetGroup = "ImportedRare",
		assetModel = "ud_zal",
		rollDisplay = {
			displayName = "Ud'zal",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "ud_zal_head",
			Torso = "ud_zal_torso",
			LeftArm = "ud_zal_left_arm",
			RightArm = "ud_zal_right_arm",
			LeftLeg = "ud_zal_left_leg",
			RightLeg = "ud_zal_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	werewolf = {
		id = "werewolf",
		displayName = "Werewolf Set",
		sourceModelName = "Werewolf",
		assetGroup = "ImportedRare",
		assetModel = "werewolf",
		rollDisplay = {
			displayName = "Werewolf",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "werewolf_head",
			Torso = "werewolf_torso",
			LeftArm = "werewolf_left_arm",
			RightArm = "werewolf_right_arm",
			LeftLeg = "werewolf_left_leg",
			RightLeg = "werewolf_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 26,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	werner_weenie = {
		id = "werner_weenie",
		displayName = "Werner Weenie Set",
		sourceModelName = "Werner Weenie",
		assetGroup = "ImportedUncommon",
		assetModel = "werner_weenie",
		rollDisplay = {
			displayName = "Werner Weenie",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 150,
			color = Color3.fromRGB(154, 246, 176),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "werner_weenie_head",
			Torso = "werner_weenie_torso",
			LeftArm = "werner_weenie_left_arm",
			RightArm = "werner_weenie_right_arm",
			LeftLeg = "werner_weenie_left_leg",
			RightLeg = "werner_weenie_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 12,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	woman = {
		id = "woman",
		displayName = "Woman Set",
		sourceModelName = "Woman",
		assetGroup = "ImportedCommon",
		assetModel = "woman",
		rollDisplay = {
			displayName = "Woman",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "woman_head",
			Torso = "woman_torso",
			LeftArm = "woman_left_arm",
			RightArm = "woman_right_arm",
			LeftLeg = "woman_left_leg",
			RightLeg = "woman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	zombie = {
		id = "zombie",
		displayName = "Zombie Set",
		sourceModelName = "Zombie",
		assetGroup = "ImportedCommon",
		assetModel = "zombie",
		rollDisplay = {
			displayName = "Zombie",
			rarity = "Basic",
			chance = 750,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "zombie_head",
			Torso = "zombie_torso",
			LeftArm = "zombie_left_arm",
			RightArm = "zombie_right_arm",
			LeftLeg = "zombie_left_leg",
			RightLeg = "zombie_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 6,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

}

return Sets
