local Sets = {
	classic = {
		id = "classic",
		displayName = "Default",
		assetGroup = "Examples",
		assetModel = "Classic",
		rollDisplay = {
			displayName = "Default",
			rarity = "Basic",
			chance = 1,
			passiveIncomePerSecond = 0,
			color = Color3.fromRGB(255, 255, 255),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "classic_head",
			Torso = "classic_torso",
			LeftArm = "classic_left_arm",
			RightArm = "classic_right_arm",
			LeftLeg = "classic_left_leg",
			RightLeg = "classic_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.1,
			rollSpeedBonus = 0.05,
		},
	},

	korblox_deathspeaker = {
		id = "korblox_deathspeaker",
		displayName = "Korblox Deathspeaker",
		sourceModelName = "Korblox Deathspeaker",
		assetGroup = "Korblox",
		assetModel = "Deathspeaker",
		rollDisplay = {
			displayName = "Korblox Deathspeaker",
			rarity = "Prime",
			chance = 16384,
			passiveIncomePerSecond = 4500,
			color = Color3.fromRGB(0, 4, 255),
			fontFace = Font.fromId(12187372382),
			fontWeight = Enum.FontWeight.Thin,
		},
		piecesByRegion = {
			Head = "korblox_deathspeaker_head",
			Torso = "korblox_deathspeaker_torso",
			LeftArm = "korblox_deathspeaker_left_arm",
			RightArm = "korblox_deathspeaker_right_arm",
			LeftLeg = "korblox_deathspeaker_left_leg",
			RightLeg = "korblox_deathspeaker_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.55,
			rollSpeedBonus = 0.3,
		},
	},

	["67_brainrot"] = {
		id = "67_brainrot",
		displayName = "67",
		sourceModelName = "67 (Brainrot)",
		assetGroup = "ImportedCommon",
		assetModel = "67_brainrot",
		rollDisplay = {
			displayName = "67",
			rarity = "Elite",
			chance = 625000,
			passiveIncomePerSecond = 118000,
			color = Color3.fromRGB(0, 203, 244),
			fontFace = Font.fromId(12187375716),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "67_brainrot_head",
			Torso = "67_brainrot_torso",
			LeftArm = "67_brainrot_left_arm",
			RightArm = "67_brainrot_right_arm",
			LeftLeg = "67_brainrot_left_leg",
			RightLeg = "67_brainrot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	absolute_unit = {
		id = "absolute_unit",
		displayName = "Absolute Unit (Fat Guy)",
		sourceModelName = "Absolute Unit",
		assetGroup = "ImportedUncommon",
		assetModel = "absolute_unit",
		rollDisplay = {
			displayName = "Absolute Unit (Fat Guy)",
			rarity = "Apex",
			chance = 2500000,
			passiveIncomePerSecond = 300000,
			color = Color3.fromRGB(67, 246, 96),
			fontFace = Font.fromId(12187377325),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "absolute_unit_head",
			Torso = "absolute_unit_torso",
			LeftArm = "absolute_unit_left_arm",
			RightArm = "absolute_unit_right_arm",
			LeftLeg = "absolute_unit_left_leg",
			RightLeg = "absolute_unit_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	banana_bro = {
		id = "banana_bro",
		displayName = "Banana Bro",
		sourceModelName = "Banana Bro",
		assetGroup = "ImportedCommon",
		assetModel = "banana_bro",
		rollDisplay = {
			displayName = "Banana Bro",
			rarity = "Elite",
			chance = 250000,
			passiveIncomePerSecond = 65000,
			color = Color3.fromRGB(244, 222, 136),
			fontFace = Font.fromId(12187367362),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "banana_bro_head",
			Torso = "banana_bro_torso",
			LeftArm = "banana_bro_left_arm",
			RightArm = "banana_bro_right_arm",
			LeftLeg = "banana_bro_left_leg",
			RightLeg = "banana_bro_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	bastion_mech_robot_recolorable = {
		id = "bastion_mech_robot_recolorable",
		displayName = "Giant Mech",
		sourceModelName = "Bastion mech robot [recolorable]",
		assetGroup = "ImportedRare",
		assetModel = "bastion_mech_robot_recolorable",
		rollDisplay = {
			displayName = "Giant Mech",
			rarity = "Apex",
			chance = 1250000,
			passiveIncomePerSecond = 190000,
			color = Color3.fromRGB(255, 204, 162),
			fontFace = Font.fromId(12187370928),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "bastion_mech_robot_recolorable_head",
			Torso = "bastion_mech_robot_recolorable_torso",
			LeftArm = "bastion_mech_robot_recolorable_left_arm",
			RightArm = "bastion_mech_robot_recolorable_right_arm",
			LeftLeg = "bastion_mech_robot_recolorable_left_leg",
			RightLeg = "bastion_mech_robot_recolorable_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	billy = {
		id = "billy",
		displayName = "Billy",
		sourceModelName = "Billy",
		assetGroup = "ImportedCommon",
		assetModel = "billy",
		rollDisplay = {
			displayName = "Billy",
			rarity = "Basic",
			chance = 256,
			passiveIncomePerSecond = 100,
			color = Color3.fromRGB(244, 237, 197),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "billy_head",
			Torso = "billy_torso",
			LeftArm = "billy_left_arm",
			RightArm = "billy_right_arm",
			LeftLeg = "billy_left_leg",
			RightLeg = "billy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	capybara = {
		id = "capybara",
		displayName = "Capybara",
		sourceModelName = "Capybara",
		assetGroup = "ImportedCommon",
		assetModel = "capybara",
		rollDisplay = {
			displayName = "Capybara",
			rarity = "Prime",
			chance = 24000,
			passiveIncomePerSecond = 6500,
			color = Color3.fromRGB(244, 222, 155),
			fontFace = Font.fromId(12187375716),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "capybara_head",
			Torso = "capybara_torso",
			LeftArm = "capybara_left_arm",
			RightArm = "capybara_right_arm",
			LeftLeg = "capybara_left_leg",
			RightLeg = "capybara_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	cat_mech = {
		id = "cat_mech",
		displayName = "Cat Mech",
		sourceModelName = "Cat Mech",
		assetGroup = "ImportedUncommon",
		assetModel = "cat_mech",
		rollDisplay = {
			displayName = "Cat Mech",
			rarity = "Elite",
			chance = 400000,
			passiveIncomePerSecond = 88000,
			color = Color3.fromRGB(246, 138, 244),
			fontFace = Font.fromId(12187371840),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "cat_mech_head",
			Torso = "cat_mech_torso",
			LeftArm = "cat_mech_left_arm",
			RightArm = "cat_mech_right_arm",
			LeftLeg = "cat_mech_left_leg",
			RightLeg = "cat_mech_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	chef_tortrdee = {
		id = "chef_tortrdee",
		displayName = "Chef Tortrdee",
		sourceModelName = "Chef Tortrdee",
		assetGroup = "ImportedUncommon",
		assetModel = "chef_tortrdee",
		rollDisplay = {
			displayName = "Chef Tortrdee",
			rarity = "Prime",
			chance = 60000,
			passiveIncomePerSecond = 17250,
			color = Color3.fromRGB(75, 246, 104),
			fontFace = Font.fromId(8836875837),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "chef_tortrdee_head",
			Torso = "chef_tortrdee_torso",
			LeftArm = "chef_tortrdee_left_arm",
			RightArm = "chef_tortrdee_right_arm",
			LeftLeg = "chef_tortrdee_left_leg",
			RightLeg = "chef_tortrdee_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	deer_monster_99_nights_in_the_forest = {
		id = "deer_monster_99_nights_in_the_forest",
		displayName = "99 Nights",
		sourceModelName = "Deer Monster (99 Nights in the Forest)",
		assetGroup = "ImportedRare",
		assetModel = "deer_monster_99_nights_in_the_forest",
		rollDisplay = {
			displayName = "99 Nights",
			rarity = "Elite",
			chance = 1000000,
			passiveIncomePerSecond = 160000,
			color = Color3.fromRGB(255, 61, 61),
			fontFace = Font.fromId(12187371991),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "deer_monster_99_nights_in_the_forest_head",
			Torso = "deer_monster_99_nights_in_the_forest_torso",
			LeftArm = "deer_monster_99_nights_in_the_forest_left_arm",
			RightArm = "deer_monster_99_nights_in_the_forest_right_arm",
			LeftLeg = "deer_monster_99_nights_in_the_forest_left_leg",
			RightLeg = "deer_monster_99_nights_in_the_forest_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	el_gato = {
		id = "el_gato",
		displayName = "El Gato",
		sourceModelName = "El Gato",
		assetGroup = "ImportedUncommon",
		assetModel = "el_gato",
		rollDisplay = {
			displayName = "El Gato",
			rarity = "Prime",
			chance = 70000,
			passiveIncomePerSecond = 22000,
			color = Color3.fromRGB(246, 192, 97),
			fontFace = Font.fromId(12187363616),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "el_gato_head",
			Torso = "el_gato_torso",
			LeftArm = "el_gato_left_arm",
			RightArm = "el_gato_right_arm",
			LeftLeg = "el_gato_left_leg",
			RightLeg = "el_gato_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	elemental_crystal_golem = {
		id = "elemental_crystal_golem",
		displayName = "Elemental Crystal Golem",
		sourceModelName = "Elemental Crystal Golem",
		assetGroup = "ImportedRare",
		assetModel = "elemental_crystal_golem",
		rollDisplay = {
			displayName = "Elemental Crystal Golem",
			rarity = "Prime",
			chance = 32768,
			passiveIncomePerSecond = 9250,
			color = Color3.fromRGB(255, 238, 48),
			fontFace = Font.fromId(12187364842),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "elemental_crystal_golem_head",
			Torso = "elemental_crystal_golem_torso",
			LeftArm = "elemental_crystal_golem_left_arm",
			RightArm = "elemental_crystal_golem_right_arm",
			LeftLeg = "elemental_crystal_golem_left_leg",
			RightLeg = "elemental_crystal_golem_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	frost_guard_general = {
		id = "frost_guard_general",
		displayName = "Frost Guard",
		sourceModelName = "Frost Guard General",
		assetGroup = "ImportedRare",
		assetModel = "frost_guard_general",
		rollDisplay = {
			displayName = "Frost Guard",
			rarity = "Clean",
			chance = 6000,
			passiveIncomePerSecond = 1500,
			color = Color3.fromRGB(199, 255, 243),
			fontFace = Font.fromId(12187368093),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "frost_guard_general_head",
			Torso = "frost_guard_general_torso",
			LeftArm = "frost_guard_general_left_arm",
			RightArm = "frost_guard_general_right_arm",
			LeftLeg = "frost_guard_general_left_leg",
			RightLeg = "frost_guard_general_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	gang_o_fries = {
		id = "gang_o_fries",
		displayName = "Fries",
		sourceModelName = "Gang O' Fries",
		assetGroup = "ImportedCommon",
		assetModel = "gang_o_fries",
		rollDisplay = {
			displayName = "Fries",
			rarity = "Prime",
			chance = 25000,
			passiveIncomePerSecond = 7250,
			color = Color3.fromRGB(244, 194, 107),
			fontFace = Font.fromId(12187374098),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "gang_o_fries_head",
			Torso = "gang_o_fries_torso",
			LeftArm = "gang_o_fries_left_arm",
			RightArm = "gang_o_fries_right_arm",
			LeftLeg = "gang_o_fries_left_leg",
			RightLeg = "gang_o_fries_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	gingerbread_man = {
		id = "gingerbread_man",
		displayName = "Gingerbread",
		sourceModelName = "Gingerbread Man",
		assetGroup = "ImportedCommon",
		assetModel = "gingerbread_man",
		rollDisplay = {
			displayName = "Gingerbread",
			rarity = "Clean",
			chance = 3000,
			passiveIncomePerSecond = 775,
			color = Color3.fromRGB(77, 244, 88),
			fontFace = Font.fromId(12187373592),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "gingerbread_man_head",
			Torso = "gingerbread_man_torso",
			LeftArm = "gingerbread_man_left_arm",
			RightArm = "gingerbread_man_right_arm",
			LeftLeg = "gingerbread_man_left_leg",
			RightLeg = "gingerbread_man_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	handsome_squidward = {
		id = "handsome_squidward",
		displayName = "Handsome Squidward",
		sourceModelName = "Handsome Squidward",
		assetGroup = "ImportedUncommon",
		assetModel = "handsome_squidward",
		rollDisplay = {
			displayName = "Handsome Squidward",
			rarity = "Elite",
			chance = 500000,
			passiveIncomePerSecond = 102000,
			color = Color3.fromRGB(0, 246, 246),
			fontFace = Font.fromId(12187375958),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "handsome_squidward_head",
			Torso = "handsome_squidward_torso",
			LeftArm = "handsome_squidward_left_arm",
			RightArm = "handsome_squidward_right_arm",
			LeftLeg = "handsome_squidward_left_leg",
			RightLeg = "handsome_squidward_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	headless_horseman = {
		id = "headless_horseman",
		displayName = "Headless Horseman",
		sourceModelName = "Headless Horseman",
		assetGroup = "ImportedLegendary",
		assetModel = "headless_horseman",
		rollDisplay = {
			displayName = "Headless Horseman",
			rarity = "Prime",
			chance = 18000,
			passiveIncomePerSecond = 5000,
			color = Color3.fromRGB(255, 94, 94),
			fontFace = Font.fromId(12187363148),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "headless_horseman_head",
			Torso = "headless_horseman_torso",
			LeftArm = "headless_horseman_left_arm",
			RightArm = "headless_horseman_right_arm",
			LeftLeg = "headless_horseman_left_leg",
			RightLeg = "headless_horseman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	heart = {
		id = "heart",
		displayName = "Heart",
		sourceModelName = "Heart",
		assetGroup = "ImportedCommon",
		assetModel = "heart",
		rollDisplay = {
			displayName = "Heart",
			rarity = "Prime",
			chance = 100000,
			passiveIncomePerSecond = 37000,
			color = Color3.fromRGB(244, 75, 156),
			fontFace = Font.fromId(8764312106),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "heart_head",
			Torso = "heart_torso",
			LeftArm = "heart_left_arm",
			RightArm = "heart_right_arm",
			LeftLeg = "heart_left_leg",
			RightLeg = "heart_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	iron_slayer = {
		id = "iron_slayer",
		displayName = "Iron Slayer",
		sourceModelName = "Iron Slayer",
		assetGroup = "ImportedRare",
		assetModel = "iron_slayer",
		rollDisplay = {
			displayName = "Iron Slayer",
			rarity = "Prime",
			chance = 50000,
			passiveIncomePerSecond = 15250,
			color = Color3.fromRGB(222, 140, 140),
			fontFace = Font.fromId(12187367901),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "iron_slayer_head",
			Torso = "iron_slayer_torso",
			LeftArm = "iron_slayer_left_arm",
			RightArm = "iron_slayer_right_arm",
			LeftLeg = "iron_slayer_left_leg",
			RightLeg = "iron_slayer_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	junkbot = {
		id = "junkbot",
		displayName = "Junkbot",
		sourceModelName = "Junkbot",
		assetGroup = "ImportedUncommon",
		assetModel = "junkbot",
		rollDisplay = {
			displayName = "Junkbot",
			rarity = "Basic",
			chance = 64,
			passiveIncomePerSecond = 35,
			color = Color3.fromRGB(244, 246, 111),
			fontFace = Font.fromId(12187360881),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "junkbot_head",
			Torso = "junkbot_torso",
			LeftArm = "junkbot_left_arm",
			RightArm = "junkbot_right_arm",
			LeftLeg = "junkbot_left_leg",
			RightLeg = "junkbot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	knights_of_redcliff_paladin = {
		id = "knights_of_redcliff_paladin",
		displayName = "Paladin",
		sourceModelName = "Knights of Redcliff: Paladin",
		assetGroup = "ImportedEpic",
		assetModel = "knights_of_redcliff_paladin",
		rollDisplay = {
			displayName = "Paladin",
			rarity = "Basic",
			chance = 128,
			passiveIncomePerSecond = 60,
			color = Color3.fromRGB(255, 152, 79),
			fontFace = Font.fromId(12187365769),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "knights_of_redcliff_paladin_head",
			Torso = "knights_of_redcliff_paladin_torso",
			LeftArm = "knights_of_redcliff_paladin_left_arm",
			RightArm = "knights_of_redcliff_paladin_right_arm",
			LeftLeg = "knights_of_redcliff_paladin_left_leg",
			RightLeg = "knights_of_redcliff_paladin_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	korblox_mage = {
		id = "korblox_mage",
		displayName = "Korblox Mage",
		sourceModelName = "Korblox Mage",
		assetGroup = "ImportedRare",
		assetModel = "korblox_mage",
		rollDisplay = {
			displayName = "Korblox Mage",
			rarity = "Prime",
			chance = 12500,
			passiveIncomePerSecond = 3500,
			color = Color3.fromRGB(53, 141, 255),
			fontFace = Font.fromId(12187365769),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "korblox_mage_head",
			Torso = "korblox_mage_torso",
			LeftArm = "korblox_mage_left_arm",
			RightArm = "korblox_mage_right_arm",
			LeftLeg = "korblox_mage_left_leg",
			RightLeg = "korblox_mage_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	los_tralaleritos_brainrot = {
		id = "los_tralaleritos_brainrot",
		displayName = "Los Tralaleritos",
		sourceModelName = "Los Tralaleritos (Brainrot)",
		assetGroup = "ImportedEpic",
		assetModel = "los_tralaleritos_brainrot",
		rollDisplay = {
			displayName = "Los Tralaleritos",
			rarity = "Prime",
			chance = 80000,
			passiveIncomePerSecond = 28500,
			color = Color3.fromRGB(74, 213, 255),
			fontFace = Font.fromId(11702779409),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "los_tralaleritos_brainrot_head",
			Torso = "los_tralaleritos_brainrot_torso",
			LeftArm = "los_tralaleritos_brainrot_left_arm",
			RightArm = "los_tralaleritos_brainrot_right_arm",
			LeftLeg = "los_tralaleritos_brainrot_left_leg",
			RightLeg = "los_tralaleritos_brainrot_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	mahoraga = {
		id = "mahoraga",
		displayName = "Mahoraga",
		sourceModelName = "Mahoraga",
		assetGroup = "ImportedLegendary",
		assetModel = "mahoraga",
		rollDisplay = {
			displayName = "Mahoraga",
			rarity = "Elite",
			chance = 800000,
			passiveIncomePerSecond = 138000,
			color = Color3.fromRGB(255, 221, 87),
			fontFace = Font.fromId(12187365104),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "mahoraga_head",
			Torso = "mahoraga_torso",
			LeftArm = "mahoraga_left_arm",
			RightArm = "mahoraga_right_arm",
			LeftLeg = "mahoraga_left_leg",
			RightLeg = "mahoraga_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	man = {
		id = "man",
		displayName = "Man",
		sourceModelName = "Man",
		assetGroup = "ImportedCommon",
		assetModel = "man",
		rollDisplay = {
			displayName = "Man",
			rarity = "Basic",
			chance = 8,
			passiveIncomePerSecond = 8,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "man_head",
			Torso = "man_torso",
			LeftArm = "man_left_arm",
			RightArm = "man_right_arm",
			LeftLeg = "man_left_leg",
			RightLeg = "man_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	mech_golem = {
		id = "mech_golem",
		displayName = "Mech (Golem)",
		sourceModelName = "Mech Golem",
		assetGroup = "ImportedRare",
		assetModel = "mech_golem",
		rollDisplay = {
			displayName = "Mech (Golem)",
			rarity = "Prime",
			chance = 75000,
			passiveIncomePerSecond = 25000,
			color = Color3.fromRGB(255, 110, 84),
			fontFace = Font.fromId(12187362120),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "mech_golem_head",
			Torso = "mech_golem_torso",
			LeftArm = "mech_golem_left_arm",
			RightArm = "mech_golem_right_arm",
			LeftLeg = "mech_golem_left_leg",
			RightLeg = "mech_golem_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	mr_roboto = {
		id = "mr_roboto",
		displayName = "Robot",
		sourceModelName = "Mr. Roboto",
		assetGroup = "ImportedUncommon",
		assetModel = "mr_roboto",
		rollDisplay = {
			displayName = "Robot",
			rarity = "Clean",
			chance = 4096,
			passiveIncomePerSecond = 1050,
			color = Color3.fromRGB(146, 176, 246),
			fontFace = Font.fromId(12187367066),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "mr_roboto_head",
			Torso = "mr_roboto_torso",
			LeftArm = "mr_roboto_left_arm",
			RightArm = "mr_roboto_right_arm",
			LeftLeg = "mr_roboto_left_leg",
			RightLeg = "mr_roboto_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	mr_toilet = {
		id = "mr_toilet",
		displayName = "Toilet",
		sourceModelName = "Mr. Toilet",
		assetGroup = "ImportedUncommon",
		assetModel = "mr_toilet",
		rollDisplay = {
			displayName = "Toilet",
			rarity = "Clean",
			chance = 9000,
			passiveIncomePerSecond = 2400,
			color = Color3.fromRGB(167, 101, 84),
			fontFace = Font.fromId(12187377325),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "mr_toilet_head",
			Torso = "mr_toilet_torso",
			LeftArm = "mr_toilet_left_arm",
			RightArm = "mr_toilet_right_arm",
			LeftLeg = "mr_toilet_left_leg",
			RightLeg = "mr_toilet_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	muscle_insane_chad_8_pack_body = {
		id = "muscle_insane_chad_8_pack_body",
		displayName = "Celestial Titan",
		sourceModelName = "Muscle Insane Chad 8 Pack Body",
		assetGroup = "ImportedEpic",
		assetModel = "muscle_insane_chad_8_pack_body",
		rollDisplay = {
			displayName = "Celestial Titan",
			rarity = "Apex",
			chance = 5000000,
			passiveIncomePerSecond = 500000,
			color = Color3.fromRGB(255, 255, 255),
			fontFace = Font.fromId(12187368317),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "muscle_insane_chad_8_pack_body_head",
			Torso = "muscle_insane_chad_8_pack_body_torso",
			LeftArm = "muscle_insane_chad_8_pack_body_left_arm",
			RightArm = "muscle_insane_chad_8_pack_body_right_arm",
			LeftLeg = "muscle_insane_chad_8_pack_body_left_leg",
			RightLeg = "muscle_insane_chad_8_pack_body_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.24,
			rollSpeedBonus = 0.11,
		},
	},

	noob_attack_mech_mobility = {
		id = "noob_attack_mech_mobility",
		displayName = "Mech (early)",
		sourceModelName = "Noob Attack: Mech Mobility",
		assetGroup = "ImportedUncommon",
		assetModel = "noob_attack_mech_mobility",
		rollDisplay = {
			displayName = "Mech (early)",
			rarity = "Clean",
			chance = 10000,
			passiveIncomePerSecond = 3000,
			color = Color3.fromRGB(122, 246, 238),
			fontFace = Font.fromId(12187371324),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "noob_attack_mech_mobility_head",
			Torso = "noob_attack_mech_mobility_torso",
			LeftArm = "noob_attack_mech_mobility_left_arm",
			RightArm = "noob_attack_mech_mobility_right_arm",
			LeftLeg = "noob_attack_mech_mobility_left_leg",
			RightLeg = "noob_attack_mech_mobility_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	paper_sketch_boy_animated = {
		id = "paper_sketch_boy_animated",
		displayName = "Paper Boy",
		sourceModelName = "Paper Sketch Boy Animated",
		assetGroup = "ImportedRare",
		assetModel = "paper_sketch_boy_animated",
		rollDisplay = {
			displayName = "Paper Boy",
			rarity = "Clean",
			chance = 9500,
			passiveIncomePerSecond = 2700,
			color = Color3.fromRGB(200, 187, 187),
			fontFace = Font.fromId(12187607493),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "paper_sketch_boy_animated_head",
			Torso = "paper_sketch_boy_animated_torso",
			LeftArm = "paper_sketch_boy_animated_left_arm",
			RightArm = "paper_sketch_boy_animated_right_arm",
			LeftLeg = "paper_sketch_boy_animated_left_leg",
			RightLeg = "paper_sketch_boy_animated_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	penguin = {
		id = "penguin",
		displayName = "Penguin",
		sourceModelName = "Penguin",
		assetGroup = "ImportedCommon",
		assetModel = "penguin",
		rollDisplay = {
			displayName = "Penguin",
			rarity = "Clean",
			chance = 2500,
			passiveIncomePerSecond = 650,
			color = Color3.fromRGB(194, 235, 244),
			fontFace = Font.fromId(12187377099),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "penguin_head",
			Torso = "penguin_torso",
			LeftArm = "penguin_left_arm",
			RightArm = "penguin_right_arm",
			LeftLeg = "penguin_left_leg",
			RightLeg = "penguin_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	pirate_swashbuckler = {
		id = "pirate_swashbuckler",
		displayName = "Pirate",
		sourceModelName = "Pirate Swashbuckler",
		assetGroup = "ImportedUncommon",
		assetModel = "pirate_swashbuckler",
		rollDisplay = {
			displayName = "Pirate",
			rarity = "Clean",
			chance = 2048,
			passiveIncomePerSecond = 550,
			color = Color3.fromRGB(172, 183, 246),
			fontFace = Font.fromId(12187371622),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "pirate_swashbuckler_head",
			Torso = "pirate_swashbuckler_torso",
			LeftArm = "pirate_swashbuckler_left_arm",
			RightArm = "pirate_swashbuckler_right_arm",
			LeftLeg = "pirate_swashbuckler_left_leg",
			RightLeg = "pirate_swashbuckler_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	potato_boy = {
		id = "potato_boy",
		displayName = "Potato Boy",
		sourceModelName = "Potato boy",
		assetGroup = "ImportedCommon",
		assetModel = "potato_boy",
		rollDisplay = {
			displayName = "Potato Boy",
			rarity = "Clean",
			chance = 1024,
			passiveIncomePerSecond = 300,
			color = Color3.fromRGB(244, 230, 179),
			fontFace = Font.fromId(11322590111),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "potato_boy_head",
			Torso = "potato_boy_torso",
			LeftArm = "potato_boy_left_arm",
			RightArm = "potato_boy_right_arm",
			LeftLeg = "potato_boy_left_leg",
			RightLeg = "potato_boy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	rig = {
		id = "rig",
		displayName = "Lego",
		sourceModelName = "Rig",
		assetGroup = "ImportedCommon",
		assetModel = "rig",
		rollDisplay = {
			displayName = "Lego",
			rarity = "Basic",
			chance = 512,
			passiveIncomePerSecond = 170,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "rig_head",
			Torso = "rig_torso",
			LeftArm = "rig_left_arm",
			RightArm = "rig_right_arm",
			LeftLeg = "rig_left_leg",
			RightLeg = "rig_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	roblox_boy = {
		id = "roblox_boy",
		displayName = "Boy",
		sourceModelName = "ROBLOX Boy",
		assetGroup = "ImportedCommon",
		assetModel = "roblox_boy",
		rollDisplay = {
			displayName = "Boy",
			rarity = "Basic",
			chance = 2,
			passiveIncomePerSecond = 2,
			color = Color3.fromRGB(185, 231, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "roblox_boy_head",
			Torso = "roblox_boy_torso",
			LeftArm = "roblox_boy_left_arm",
			RightArm = "roblox_boy_right_arm",
			LeftLeg = "roblox_boy_left_leg",
			RightLeg = "roblox_boy_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	roblox_girl = {
		id = "roblox_girl",
		displayName = "Girl",
		sourceModelName = "ROBLOX Girl",
		assetGroup = "ImportedCommon",
		assetModel = "roblox_girl",
		rollDisplay = {
			displayName = "Girl",
			rarity = "Basic",
			chance = 4,
			passiveIncomePerSecond = 4,
			color = Color3.fromRGB(244, 190, 219),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "roblox_girl_head",
			Torso = "roblox_girl_torso",
			LeftArm = "roblox_girl_left_arm",
			RightArm = "roblox_girl_right_arm",
			LeftLeg = "roblox_girl_left_leg",
			RightLeg = "roblox_girl_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	robloxian_2_0 = {
		id = "robloxian_2_0",
		displayName = "Robloxian",
		sourceModelName = "Robloxian 2.0",
		assetGroup = "ImportedUncommon",
		assetModel = "robloxian_2_0",
		rollDisplay = {
			displayName = "Robloxian",
			rarity = "Basic",
			chance = 32,
			passiveIncomePerSecond = 20,
			color = Color3.fromRGB(141, 181, 246),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "robloxian_2_0_head",
			Torso = "robloxian_2_0_torso",
			LeftArm = "robloxian_2_0_left_arm",
			RightArm = "robloxian_2_0_right_arm",
			LeftLeg = "robloxian_2_0_left_leg",
			RightLeg = "robloxian_2_0_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	shrek = {
		id = "shrek",
		displayName = "Shrek",
		sourceModelName = "SHREK",
		assetGroup = "ImportedCommon",
		assetModel = "shrek",
		rollDisplay = {
			displayName = "Shrek",
			rarity = "Elite",
			chance = 200000,
			passiveIncomePerSecond = 56000,
			color = Color3.fromRGB(57, 244, 44),
			fontFace = Font.fromId(11322590111),
			fontWeight = Enum.FontWeight.ExtraBold,
		},
		piecesByRegion = {
			Head = "shrek_head",
			Torso = "shrek_torso",
			LeftArm = "shrek_left_arm",
			RightArm = "shrek_right_arm",
			LeftLeg = "shrek_left_leg",
			RightLeg = "shrek_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	skeleton = {
		id = "skeleton",
		displayName = "Skeleton",
		sourceModelName = "Skeleton",
		assetGroup = "ImportedCommon",
		assetModel = "skeleton",
		rollDisplay = {
			displayName = "Skeleton",
			rarity = "Clean",
			chance = 3600,
			passiveIncomePerSecond = 900,
			color = Color3.fromRGB(244, 232, 197),
			fontFace = Font.fromId(16658237174),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "skeleton_head",
			Torso = "skeleton_torso",
			LeftArm = "skeleton_left_arm",
			RightArm = "skeleton_right_arm",
			LeftLeg = "skeleton_left_leg",
			RightLeg = "skeleton_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	smiling_freak = {
		id = "smiling_freak",
		displayName = "Smiling Freak",
		sourceModelName = "Smiling Freak",
		assetGroup = "ImportedRare",
		assetModel = "smiling_freak",
		rollDisplay = {
			displayName = "Smiling Freak",
			rarity = "Prime",
			chance = 90000,
			passiveIncomePerSecond = 32500,
			color = Color3.fromRGB(193, 193, 193),
			fontFace = Font.fromId(12187372382),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "smiling_freak_head",
			Torso = "smiling_freak_torso",
			LeftArm = "smiling_freak_left_arm",
			RightArm = "smiling_freak_right_arm",
			LeftLeg = "smiling_freak_left_leg",
			RightLeg = "smiling_freak_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	snow_gentleman = {
		id = "snow_gentleman",
		displayName = "Snowman",
		sourceModelName = "Snow Gentleman",
		assetGroup = "ImportedUncommon",
		assetModel = "snow_gentleman",
		rollDisplay = {
			displayName = "Snowman",
			rarity = "Clean",
			chance = 5000,
			passiveIncomePerSecond = 1250,
			color = Color3.fromRGB(164, 231, 246),
			fontFace = Font.fromId(12187364648),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "snow_gentleman_head",
			Torso = "snow_gentleman_torso",
			LeftArm = "snow_gentleman_left_arm",
			RightArm = "snow_gentleman_right_arm",
			LeftLeg = "snow_gentleman_left_leg",
			RightLeg = "snow_gentleman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	snow_queen = {
		id = "snow_queen",
		displayName = "Snow Queen",
		sourceModelName = "Snow Queen",
		assetGroup = "ImportedRare",
		assetModel = "snow_queen",
		rollDisplay = {
			displayName = "Snow Queen",
			rarity = "Clean",
			chance = 7500,
			passiveIncomePerSecond = 1800,
			color = Color3.fromRGB(193, 255, 253),
			fontFace = Font.fromId(12187361943),
			fontWeight = Enum.FontWeight.ExtraBold,
		},
		piecesByRegion = {
			Head = "snow_queen_head",
			Torso = "snow_queen_torso",
			LeftArm = "snow_queen_left_arm",
			RightArm = "snow_queen_right_arm",
			LeftLeg = "snow_queen_left_leg",
			RightLeg = "snow_queen_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	steamboat_mouse = {
		id = "steamboat_mouse",
		displayName = "Steamboat Willie",
		sourceModelName = "Steamboat Mouse",
		assetGroup = "ImportedCommon",
		assetModel = "steamboat_mouse",
		rollDisplay = {
			displayName = "Steamboat Willie",
			rarity = "Prime",
			chance = 45000,
			passiveIncomePerSecond = 13500,
			color = Color3.fromRGB(220, 220, 220),
			fontFace = Font.fromId(12187367666),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "steamboat_mouse_head",
			Torso = "steamboat_mouse_torso",
			LeftArm = "steamboat_mouse_left_arm",
			RightArm = "steamboat_mouse_right_arm",
			LeftLeg = "steamboat_mouse_left_leg",
			RightLeg = "steamboat_mouse_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	stinky_monkey = {
		id = "stinky_monkey",
		displayName = "Stinky Monkey",
		sourceModelName = "Stinky Monkey",
		assetGroup = "ImportedUncommon",
		assetModel = "stinky_monkey",
		rollDisplay = {
			displayName = "Stinky Monkey",
			rarity = "Elite",
			chance = 150000,
			passiveIncomePerSecond = 48000,
			color = Color3.fromRGB(115, 246, 119),
			fontFace = Font.fromId(12187376174),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "stinky_monkey_head",
			Torso = "stinky_monkey_torso",
			LeftArm = "stinky_monkey_left_arm",
			RightArm = "stinky_monkey_right_arm",
			LeftLeg = "stinky_monkey_left_leg",
			RightLeg = "stinky_monkey_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	superhero = {
		id = "superhero",
		displayName = "Superhero",
		sourceModelName = "Superhero",
		assetGroup = "ImportedUncommon",
		assetModel = "superhero",
		rollDisplay = {
			displayName = "Superhero",
			rarity = "Clean",
			chance = 1500,
			passiveIncomePerSecond = 400,
			color = Color3.fromRGB(246, 210, 137),
			fontFace = Font.fromId(12187370000),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "superhero_head",
			Torso = "superhero_torso",
			LeftArm = "superhero_left_arm",
			RightArm = "superhero_right_arm",
			LeftLeg = "superhero_left_leg",
			RightLeg = "superhero_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	supreme_claus = {
		id = "supreme_claus",
		displayName = "Supreme Claus",
		sourceModelName = "Supreme Claus",
		assetGroup = "ImportedUncommon",
		assetModel = "supreme_claus",
		rollDisplay = {
			displayName = "Supreme Claus",
			rarity = "Prime",
			chance = 20000,
			passiveIncomePerSecond = 5750,
			color = Color3.fromRGB(246, 126, 126),
			fontFace = Font.fromId(12187370000),
			fontWeight = Enum.FontWeight.ExtraBold,
		},
		piecesByRegion = {
			Head = "supreme_claus_head",
			Torso = "supreme_claus_torso",
			LeftArm = "supreme_claus_left_arm",
			RightArm = "supreme_claus_right_arm",
			LeftLeg = "supreme_claus_left_leg",
			RightLeg = "supreme_claus_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	tentacled_alien = {
		id = "tentacled_alien",
		displayName = "Alien",
		sourceModelName = "Tentacled Alien",
		assetGroup = "ImportedRare",
		assetModel = "tentacled_alien",
		rollDisplay = {
			displayName = "Alien",
			rarity = "Clean",
			chance = 8192,
			passiveIncomePerSecond = 2100,
			color = Color3.fromRGB(230, 106, 255),
			fontFace = Font.fromId(12187362578),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "tentacled_alien_head",
			Torso = "tentacled_alien_torso",
			LeftArm = "tentacled_alien_left_arm",
			RightArm = "tentacled_alien_right_arm",
			LeftLeg = "tentacled_alien_left_leg",
			RightLeg = "tentacled_alien_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_gnomsky_brothers = {
		id = "the_gnomsky_brothers",
		displayName = "Gnomsky Brothers",
		sourceModelName = "The Gnomsky Brothers",
		assetGroup = "ImportedRare",
		assetModel = "the_gnomsky_brothers",
		rollDisplay = {
			displayName = "Gnomsky Brothers",
			rarity = "Prime",
			chance = 30000,
			passiveIncomePerSecond = 8250,
			color = Color3.fromRGB(114, 255, 130),
			fontFace = Font.fromId(12187371622),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "the_gnomsky_brothers_head",
			Torso = "the_gnomsky_brothers_torso",
			LeftArm = "the_gnomsky_brothers_left_arm",
			RightArm = "the_gnomsky_brothers_right_arm",
			LeftLeg = "the_gnomsky_brothers_left_leg",
			RightLeg = "the_gnomsky_brothers_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_overseer = {
		id = "the_overseer",
		displayName = "Overseer",
		sourceModelName = "The Overseer",
		assetGroup = "ImportedRare",
		assetModel = "the_overseer",
		rollDisplay = {
			displayName = "Overseer",
			rarity = "Prime",
			chance = 15000,
			passiveIncomePerSecond = 4000,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187376357),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "the_overseer_head",
			Torso = "the_overseer_torso",
			LeftArm = "the_overseer_left_arm",
			RightArm = "the_overseer_right_arm",
			LeftLeg = "the_overseer_left_leg",
			RightLeg = "the_overseer_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	the_rulk_custom_colour = {
		id = "the_rulk_custom_colour",
		displayName = "The Rulk",
		sourceModelName = "The Rulk - Custom Colour",
		assetGroup = "ImportedLegendary",
		assetModel = "the_rulk_custom_colour",
		rollDisplay = {
			displayName = "The Rulk",
			rarity = "Elite",
			chance = 300000,
			passiveIncomePerSecond = 75000,
			color = Color3.fromRGB(255, 214, 92),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Heavy,
		},
		piecesByRegion = {
			Head = "the_rulk_custom_colour_head",
			Torso = "the_rulk_custom_colour_torso",
			LeftArm = "the_rulk_custom_colour_left_arm",
			RightArm = "the_rulk_custom_colour_right_arm",
			LeftLeg = "the_rulk_custom_colour_left_leg",
			RightLeg = "the_rulk_custom_colour_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.4,
			rollSpeedBonus = 0.18,
		},
	},

	ud_zal = {
		id = "ud_zal",
		displayName = "Ud'zal",
		sourceModelName = "Ud'zal",
		assetGroup = "ImportedRare",
		assetModel = "ud_zal",
		rollDisplay = {
			displayName = "Ud'zal",
			rarity = "Prime",
			chance = 36000,
			passiveIncomePerSecond = 10500,
			color = Color3.fromRGB(143, 106, 255),
			fontFace = Font.fromId(12187368843),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "ud_zal_head",
			Torso = "ud_zal_torso",
			LeftArm = "ud_zal_left_arm",
			RightArm = "ud_zal_right_arm",
			LeftLeg = "ud_zal_left_leg",
			RightLeg = "ud_zal_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	werewolf = {
		id = "werewolf",
		displayName = "Werewolf",
		sourceModelName = "Werewolf",
		assetGroup = "ImportedRare",
		assetModel = "werewolf",
		rollDisplay = {
			displayName = "Werewolf",
			rarity = "Clean",
			chance = 1250,
			passiveIncomePerSecond = 350,
			color = Color3.fromRGB(119, 198, 255),
			fontFace = Font.fromId(12187375194),
			fontWeight = Enum.FontWeight.Medium,
		},
		piecesByRegion = {
			Head = "werewolf_head",
			Torso = "werewolf_torso",
			LeftArm = "werewolf_left_arm",
			RightArm = "werewolf_right_arm",
			LeftLeg = "werewolf_left_leg",
			RightLeg = "werewolf_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.14,
			rollSpeedBonus = 0.07,
		},
	},

	werner_weenie = {
		id = "werner_weenie",
		displayName = "Werner Weenie",
		sourceModelName = "Werner Weenie",
		assetGroup = "ImportedUncommon",
		assetModel = "werner_weenie",
		rollDisplay = {
			displayName = "Werner Weenie",
			rarity = "Prime",
			chance = 40000,
			passiveIncomePerSecond = 12000,
			color = Color3.fromRGB(246, 124, 99),
			fontFace = Font.fromId(12187375716),
			fontWeight = Enum.FontWeight.Bold,
		},
		piecesByRegion = {
			Head = "werner_weenie_head",
			Torso = "werner_weenie_torso",
			LeftArm = "werner_weenie_left_arm",
			RightArm = "werner_weenie_right_arm",
			LeftLeg = "werner_weenie_left_leg",
			RightLeg = "werner_weenie_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.08,
			rollSpeedBonus = 0.04,
		},
	},

	woman = {
		id = "woman",
		displayName = "Woman",
		sourceModelName = "Woman",
		assetGroup = "ImportedCommon",
		assetModel = "woman",
		rollDisplay = {
			displayName = "Woman",
			rarity = "Basic",
			chance = 16,
			passiveIncomePerSecond = 12,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "woman_head",
			Torso = "woman_torso",
			LeftArm = "woman_left_arm",
			RightArm = "woman_right_arm",
			LeftLeg = "woman_left_leg",
			RightLeg = "woman_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

	zombie = {
		id = "zombie",
		displayName = "Zombie",
		sourceModelName = "Zombie",
		assetGroup = "ImportedCommon",
		assetModel = "zombie",
		rollDisplay = {
			displayName = "Zombie",
			rarity = "Clean",
			chance = 1800,
			passiveIncomePerSecond = 475,
			color = Color3.fromRGB(154, 244, 141),
			fontFace = Font.fromId(12187368625),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "zombie_head",
			Torso = "zombie_torso",
			LeftArm = "zombie_left_arm",
			RightArm = "zombie_right_arm",
			LeftLeg = "zombie_left_leg",
			RightLeg = "zombie_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},
	brick_body_r6 = {
		id = "brick_body_r6",
		displayName = "Brick Body R6",
		sourceModelName = "Brick Body R6",
		assetGroup = "ImportedCommon",
		assetModel = "brick_body_r6",
		rollDisplay = {
			displayName = "Brick Body R6",
			rarity = "Basic",
			chance = 512,
			passiveIncomePerSecond = 170,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "brick_body_r6_head",
			Torso = "brick_body_r6_torso",
			LeftArm = "brick_body_r6_left_arm",
			RightArm = "brick_body_r6_right_arm",
			LeftLeg = "brick_body_r6_left_leg",
			RightLeg = "brick_body_r6_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},
	davy_bazooka = {
		id = "davy_bazooka",
		displayName = "Davy Bazooka",
		sourceModelName = "Davy Bazooka",
		assetGroup = "ImportedCommon",
		assetModel = "davy_bazooka",
		rollDisplay = {
			displayName = "Davy Bazooka",
			rarity = "Basic",
			chance = 512,
			passiveIncomePerSecond = 170,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "davy_bazooka_head",
			Torso = "davy_bazooka_torso",
			LeftArm = "davy_bazooka_left_arm",
			RightArm = "davy_bazooka_right_arm",
			LeftLeg = "davy_bazooka_left_leg",
			RightLeg = "davy_bazooka_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},
	tung_tung_sahur = {
		id = "tung_tung_sahur",
		displayName = "TUNG TUNG  SAHUR",
		sourceModelName = "TUNG TUNG  SAHUR",
		assetGroup = "ImportedCommon",
		assetModel = "tung_tung_sahur",
		rollDisplay = {
			displayName = "TUNG TUNG  SAHUR",
			rarity = "Basic",
			chance = 512,
			passiveIncomePerSecond = 170,
			color = Color3.fromRGB(244, 244, 244),
			fontFace = Font.fromId(12187375422),
			fontWeight = Enum.FontWeight.SemiBold,
		},
		piecesByRegion = {
			Head = "tung_tung_sahur_head",
			Torso = "tung_tung_sahur_torso",
			LeftArm = "tung_tung_sahur_left_arm",
			RightArm = "tung_tung_sahur_right_arm",
			LeftLeg = "tung_tung_sahur_left_leg",
			RightLeg = "tung_tung_sahur_right_leg",
		},
		fullSetBonus = {
			passiveIncomePerSecond = 0,
			luckBonus = 0.05,
			rollSpeedBonus = 0.025,
		},
	},

}

return Sets